
Vagrant.configure("2") do |config|

	config.vm.box = "geerlingguy/ubuntu1804"
	config.vm.network "public_network", ip: "192.168.0.15"

	config.vm.provider "virtualbox" do |vb|
		vb.memory = 4096
		vb.cpus = 3
	end

	config.vm.provision "shell", inline: <<-SHELL
		
		echo "\n---------------------------------------- Virtual Machine created by Andrey as a part of HW03\n"
		echo "---------------------------------------- Removing Python2.7\n"

		sudo apt-get remove python2.7 -y
		sudo apt-get remove python2.7* -y

		sudo apt-get remove --purge python2.7 -y
		sudo apt-get remove --purge python2.7* -y

		sudo apt-get purge python2.7 -y
		sudo apt-get purge python2.7* -y
				
		echo "\n---------------------------------------- Installation python3\n"
		sudo apt-get update -y
		sudo ln -s /usr/bin/python3 /usr/bin/python
		
		python --version
		
		echo "\n---------------------------------------- Installation python3-pip\n"
		sudo apt install -y python3-pip
		sudo ln -s /usr/bin/pip3 /usr/bin/pip

		pip --version
		
		echo "\n---------------------------------------- Installation psycopg2\n"
		sudo apt-get update -y
		sudo apt-get install -y libpq-dev python-dev
		sudo pip install psycopg2
		
		echo "\n---------------------------------------- Installation Django\n"		
		pip3 install Django
		
		echo "\n---------------------------------------- Create user andrey\n"	
		pass=$(perl -e 'print crypt("infodba", "password")' $password)
		echo $pass
		useradd -m -p "$pass" "andrey"
		
		echo "\n---------------------------------------- Copy andreys_empty.txt from host to virtualbox /home/andrey\n"	
		cp /vagrant/andreys_empty.txt /home/andrey/andreys_empty.txt
		sudo chmod 777 /home/andrey/andreys_empty.txt

	SHELL
end
